title: Mike Ion
email: mikeion@umich.edu
description: >-
  Mike Ion — statistical methods for evaluating language models.
url: "https://mikeion.com"
author: Mike Ion

markdown: kramdown
permalink: /:title/
timezone: America/New_York

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - env
  - test_posts
  - vendor

plugins:
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "index.html"
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:slug/
